version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: "redis"
    ports:
      - "6379:6379"
  elasticsearch:
    image: "elastic"
    environment:
      - cluster.name=elastic-udt-cluster
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elasticpass
      - discovery.type=single-node
      - xpack.security.enabled=true
      - node.name=es01
      - bootstrap.memory_lock=true
      #- node.max_local_storage_nodes=4
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"