version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: "redis"
    ports:
      - "6379:6379"
  elasticsearch:
    image: "elastic"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"